### PR TITLE
Work with gzip requests fixed

### PR DESCRIPTION
**Pull request by StyleT**
getBody method always returns decoded string so decompressResponse method is useless.

### CODE REVIEW

**Comment by StyleT** [comment]
It seems that unit test also should be updated, but I'm not sure how (because I saw that they follow some standards). However this code works correctly on production server.

**Comment by bakura10** [comment]
Hi @StyleT,

Thank you for the fix. As you said, you'll need to update the test. You can see the failing test here: https://travis-ci.org/zf-fr/zfr-prerender/jobs/70649939#L189 (that basically needs to be removed if this PR is merged).

While you're at it, could you please add PHP 5.6 in the test matrix here: https://github.com/zf-fr/zfr-prerender/blob/master/.travis.yml#L5?

Thanks in advance

@thoop , can you just please have a look at this PR too, and confirm me that Prerender will actually return an uncompress response if ask for Gzip ? That seems a bit strange to me, what is the point of Gzip if Prerender actually already returns an uncompress answer? Or @StyleT , maybe ZF client uncompress it under the hood?

**Comment by StyleT** [comment]
@bakura10 yes, you're right, ZF client will uncompress it under the hood. 
```php
public function getBody() { //Zend\Http\Response

    //...

    $contentEncoding = $this->getHeaders()->get('Content-Encoding');

    if (!empty($contentEncoding)) {
        $contentEncoding = $contentEncoding->getFieldValue();
        if ($contentEncoding =='gzip') {
            $body = $this->decodeGzip($body);
        } elseif ($contentEncoding == 'deflate') {
           $body = $this->decodeDeflate($body);
    }

    //...

}
```

**Comment by bakura10** [comment]
Haaa yeah you're right ^^.

So you'll just need to update the tests ;).

**Comment by StyleT** [comment]
@bakura10 If I understand you correctly, I should just remove `ZfrPrerenderTest\Mvc\PrerenderListenerTest::testCanUncompressGzipResponses` test?

**Comment by StyleT** [comment]
So what about pull request? Cay anyone mege it?

**Comment by bakura10** [comment]
Merged, sorry for the delay! ;) I've just tagged as 3.1.1. Tahnks!

**Pull request merged**
